import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "~/i18n/routing";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode;}>) {



  return (
    <html className={GeistSans.variable}>
      <body className="min-h-screen">
        <TRPCReactProvider>
            {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
